<?php

namespace AppBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function cmdOrderByDate($idUser){
        $query = CommandeRepository::createQueryBuilder('c')
            ->where('c.supp = :supp')
            ->innerJoin('c.idUser', 'u', 'WITH', 'u.id ='.$idUser)
            ->orderBy('c.date', 'desc')
            ->setParameter('supp', 0)
            ->getQuery();
        return $query->getResult();
    }


    public function cmdAttenteByDate(){
        $query = $this->getEntityManager()->createQuery('SELECT c from AppBundle:Commande c 
        where c.etat = :e 
        group by c.idUser
        order by c.date ')
            ->setParameter('e',"En cours");
        return $query->getResult();
    }

        public function getNb(){
            $query = $this->getEntityManager()->createQuery('select COUNT (c.id) from AppBundle:Commande c 
        where c.etat = :e')
                ->setParameter('e',"En cours");
            return $query->getSingleScalarResult();
        }

        public function byDate($search){
            $query = $this::createQueryBuilder('p')
                ->where('p.date like :date')
                ->setParameter('date','%'.$search.'%')
                ->getQuery();
            return $query->getResult();
        }

}
