<?php

namespace AppBundle\Repository;

/**
 * CommandeGMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeGMSRepository extends \Doctrine\ORM\EntityRepository
{
    public function cmdOrderByDate($idUser){
        $query = CommandeGMSRepository::createQueryBuilder('c')
            ->where('c.supp = :supp')
            ->innerJoin('c.idUser', 'u', 'WITH', 'u.id ='.$idUser)
            ->orderBy('c.date', 'asc')
            ->setParameter('supp', 0)
            ->getQuery();
        return $query->getResult();
    }

    public function getNb(){
        $query = $this->getEntityManager()->createQuery('select COUNT (DISTINCT c.idUser) from AppBundle:CommandeGMS c 
        where c.etat = :e')
            ->setParameter('e',"En cours");
        return $query->getSingleScalarResult();
    }

    public function cmdAttenteByDate(){
        $query = $this->getEntityManager()->createQuery('SELECT c from AppBundle:CommandeGMS c 
        where c.etat = :e 
        group by c.idUser
        order by c.date ')
        ->setParameter('e',"En cours");
        return $query->getResult();
    }

    public function byDate($search){
        $query = $this::createQueryBuilder('p')
            ->where('p.date like :date')
            ->setParameter('date','%'.$search.'%')
            ->getQuery();
        return $query->getResult();
    }

}
