<?php

namespace AppBundle\Repository;

/**
 * ParticulierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticulierRepository extends \Doctrine\ORM\EntityRepository
{
}
