<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Produit_Particulier;

/**
 * Produit_ParticulierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_ParticulierRepository extends \Doctrine\ORM\EntityRepository
{
    public function byRef($ref){
        $query = $this::createQueryBuilder('p')
            ->where('p.reference like :reference')
            ->setParameter('reference','%'.$ref.'%')
            ->getQuery();
        return $query->getResult();
    }

    public function byLibelle($ref){
        $query = $this::createQueryBuilder('p')
            ->where('p.libelle like :libelle')
            ->setParameter('libelle','%'.$ref.'%')
            ->getQuery();
        return $query->getResult();
    }
}
