<?php

namespace AppBundle\Repository;

/**
 * Produit_GMSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Produit_GMSRepository extends \Doctrine\ORM\EntityRepository
{
}
