<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function byGMS(){
        $query = $this::createQueryBuilder('p')
            ->where('p.produitgms is not null')
            ->getQuery();
        return $query->getResult();
    }

    public function byCHR(){
        $query = $this::createQueryBuilder('p')
            ->where('p.produitchr is not null')
            ->getQuery();
        return $query->getResult();
    }
}
