# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    AppBundle\Entity\User: plaintext
    AppBundle\Entity\UserParticculier:
      algorithm: bcrypt
      cost:      15

  role_hierarchy:
      ROLE_CHR: ROLE_USER
      ROLE_GMS: ROLE_USER
      ROLE_ADMIN: ROLE_ADMIN

  providers:
      in_memory:
        memory:

      main:
        entity:
          class:    AppBundle\Entity\User
          property: username


  firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false


  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    - { path: /register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: /register_part, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


